export interface DataRecord {
  id: number;
  gender: "Male" | "Female";
  age: number;
  city: string;
  profession: string;
  academicPressure: number;
  workPressure: number;
  cgpa: number;
  studySatisfaction: number;
  jobSatisfaction: number;
  sleepDuration: string;
  dietaryHabits: string;
  degree: string;
  suicidalThoughts: "Yes" | "No";
  workStudyHours: number;
  financialStress: number;
  familyHistory: "Yes" | "No";
  depression: 0 | 1;
}

export const sampleData: DataRecord[] = [
  { id: 1, gender: "Male", age: 18, city: "Varanasi", profession: "Student", academicPressure: 3, workPressure: 0, cgpa: 7.63, studySatisfaction: 2, jobSatisfaction: 0, sleepDuration: "5-6 hours", dietaryHabits: "Moderate", degree: "B.Tech", suicidalThoughts: "Yes", workStudyHours: 3, financialStress: 2, familyHistory: "Yes", depression: 1 },
  { id: 2, gender: "Female", age: 21, city: "Srinagar", profession: "Student", academicPressure: 2, workPressure: 0, cgpa: 5.58, studySatisfaction: 3, jobSatisfaction: 0, sleepDuration: "7-8 hours", dietaryHabits: "Healthy", degree: "B.Arch", suicidalThoughts: "No", workStudyHours: 2, financialStress: 3, familyHistory: "No", depression: 0 },
  { id: 3, gender: "Male", age: 24, city: "Lucknow", profession: "Student", academicPressure: 5, workPressure: 0, cgpa: 6.2, studySatisfaction: 1, jobSatisfaction: 0, sleepDuration: "Less than 5 hours", dietaryHabits: "Unhealthy", degree: "M.Tech", suicidalThoughts: "Yes", workStudyHours: 8, financialStress: 5, familyHistory: "Yes", depression: 1 },
  { id: 4, gender: "Female", age: 19, city: "Delhi", profession: "Student", academicPressure: 1, workPressure: 0, cgpa: 8.45, studySatisfaction: 4, jobSatisfaction: 0, sleepDuration: "7-8 hours", dietaryHabits: "Healthy", degree: "B.Com", suicidalThoughts: "No", workStudyHours: 4, financialStress: 1, familyHistory: "No", depression: 0 },
  { id: 5, gender: "Male", age: 22, city: "Mumbai", profession: "Student", academicPressure: 4, workPressure: 0, cgpa: 5.9, studySatisfaction: 2, jobSatisfaction: 0, sleepDuration: "5-6 hours", dietaryHabits: "Moderate", degree: "B.Sc", suicidalThoughts: "Yes", workStudyHours: 6, financialStress: 4, familyHistory: "No", depression: 1 },
  { id: 6, gender: "Female", age: 20, city: "Pune", profession: "Student", academicPressure: 3, workPressure: 0, cgpa: 7.1, studySatisfaction: 3, jobSatisfaction: 0, sleepDuration: "7-8 hours", dietaryHabits: "Healthy", degree: "B.Tech", suicidalThoughts: "No", workStudyHours: 5, financialStress: 2, familyHistory: "No", depression: 0 },
  { id: 7, gender: "Male", age: 23, city: "Kolkata", profession: "Student", academicPressure: 5, workPressure: 0, cgpa: 4.8, studySatisfaction: 1, jobSatisfaction: 0, sleepDuration: "Less than 5 hours", dietaryHabits: "Unhealthy", degree: "MBA", suicidalThoughts: "Yes", workStudyHours: 10, financialStress: 5, familyHistory: "Yes", depression: 1 },
  { id: 8, gender: "Female", age: 18, city: "Bangalore", profession: "Student", academicPressure: 2, workPressure: 0, cgpa: 8.9, studySatisfaction: 5, jobSatisfaction: 0, sleepDuration: "More than 8 hours", dietaryHabits: "Healthy", degree: "B.Tech", suicidalThoughts: "No", workStudyHours: 3, financialStress: 1, familyHistory: "No", depression: 0 },
  { id: 9, gender: "Male", age: 25, city: "Hyderabad", profession: "Working Professional", academicPressure: 0, workPressure: 4, cgpa: 6.5, studySatisfaction: 0, jobSatisfaction: 2, sleepDuration: "5-6 hours", dietaryHabits: "Moderate", degree: "M.Sc", suicidalThoughts: "No", workStudyHours: 9, financialStress: 4, familyHistory: "Yes", depression: 1 },
  { id: 10, gender: "Female", age: 20, city: "Chennai", profession: "Student", academicPressure: 4, workPressure: 0, cgpa: 6.0, studySatisfaction: 2, jobSatisfaction: 0, sleepDuration: "5-6 hours", dietaryHabits: "Unhealthy", degree: "B.Sc", suicidalThoughts: "Yes", workStudyHours: 7, financialStress: 3, familyHistory: "No", depression: 1 },
  { id: 11, gender: "Male", age: 19, city: "Jaipur", profession: "Student", academicPressure: 1, workPressure: 0, cgpa: 9.1, studySatisfaction: 5, jobSatisfaction: 0, sleepDuration: "7-8 hours", dietaryHabits: "Healthy", degree: "B.Com", suicidalThoughts: "No", workStudyHours: 2, financialStress: 1, familyHistory: "No", depression: 0 },
  { id: 12, gender: "Female", age: 22, city: "Ahmedabad", profession: "Student", academicPressure: 5, workPressure: 0, cgpa: 5.3, studySatisfaction: 1, jobSatisfaction: 0, sleepDuration: "Less than 5 hours", dietaryHabits: "Unhealthy", degree: "B.Tech", suicidalThoughts: "Yes", workStudyHours: 8, financialStress: 5, familyHistory: "Yes", depression: 1 },
  { id: 13, gender: "Male", age: 21, city: "Chandigarh", profession: "Student", academicPressure: 3, workPressure: 0, cgpa: 7.5, studySatisfaction: 3, jobSatisfaction: 0, sleepDuration: "7-8 hours", dietaryHabits: "Moderate", degree: "BBA", suicidalThoughts: "No", workStudyHours: 4, financialStress: 2, familyHistory: "No", depression: 0 },
  { id: 14, gender: "Female", age: 26, city: "Nagpur", profession: "Working Professional", academicPressure: 0, workPressure: 5, cgpa: 5.8, studySatisfaction: 0, jobSatisfaction: 1, sleepDuration: "Less than 5 hours", dietaryHabits: "Unhealthy", degree: "M.Tech", suicidalThoughts: "Yes", workStudyHours: 11, financialStress: 5, familyHistory: "Yes", depression: 1 },
  { id: 15, gender: "Male", age: 20, city: "Indore", profession: "Student", academicPressure: 2, workPressure: 0, cgpa: 8.0, studySatisfaction: 4, jobSatisfaction: 0, sleepDuration: "7-8 hours", dietaryHabits: "Healthy", degree: "B.Sc", suicidalThoughts: "No", workStudyHours: 5, financialStress: 2, familyHistory: "No", depression: 0 },
  { id: 16, gender: "Female", age: 19, city: "Patna", profession: "Student", academicPressure: 4, workPressure: 0, cgpa: 6.3, studySatisfaction: 2, jobSatisfaction: 0, sleepDuration: "5-6 hours", dietaryHabits: "Moderate", degree: "B.Tech", suicidalThoughts: "No", workStudyHours: 6, financialStress: 3, familyHistory: "No", depression: 0 },
  { id: 17, gender: "Male", age: 24, city: "Bhopal", profession: "Student", academicPressure: 5, workPressure: 0, cgpa: 4.5, studySatisfaction: 1, jobSatisfaction: 0, sleepDuration: "Less than 5 hours", dietaryHabits: "Unhealthy", degree: "M.Com", suicidalThoughts: "Yes", workStudyHours: 9, financialStress: 5, familyHistory: "Yes", depression: 1 },
  { id: 18, gender: "Female", age: 21, city: "Kochi", profession: "Student", academicPressure: 2, workPressure: 0, cgpa: 7.8, studySatisfaction: 4, jobSatisfaction: 0, sleepDuration: "7-8 hours", dietaryHabits: "Healthy", degree: "B.Arch", suicidalThoughts: "No", workStudyHours: 4, financialStress: 1, familyHistory: "No", depression: 0 },
  { id: 19, gender: "Male", age: 27, city: "Guwahati", profession: "Working Professional", academicPressure: 0, workPressure: 3, cgpa: 7.0, studySatisfaction: 0, jobSatisfaction: 3, sleepDuration: "5-6 hours", dietaryHabits: "Moderate", degree: "MBA", suicidalThoughts: "No", workStudyHours: 8, financialStress: 3, familyHistory: "No", depression: 0 },
  { id: 20, gender: "Female", age: 18, city: "Ranchi", profession: "Student", academicPressure: 5, workPressure: 0, cgpa: 5.0, studySatisfaction: 1, jobSatisfaction: 0, sleepDuration: "Less than 5 hours", dietaryHabits: "Unhealthy", degree: "B.Sc", suicidalThoughts: "Yes", workStudyHours: 7, financialStress: 4, familyHistory: "Yes", depression: 1 },
  { id: 21, gender: "Male", age: 20, city: "Dehradun", profession: "Student", academicPressure: 3, workPressure: 0, cgpa: 7.2, studySatisfaction: 3, jobSatisfaction: 0, sleepDuration: "7-8 hours", dietaryHabits: "Moderate", degree: "B.Tech", suicidalThoughts: "No", workStudyHours: 5, financialStress: 2, familyHistory: "No", depression: 0 },
  { id: 22, gender: "Female", age: 23, city: "Thiruvananthapuram", profession: "Student", academicPressure: 4, workPressure: 0, cgpa: 6.7, studySatisfaction: 2, jobSatisfaction: 0, sleepDuration: "5-6 hours", dietaryHabits: "Moderate", degree: "M.Sc", suicidalThoughts: "Yes", workStudyHours: 6, financialStress: 3, familyHistory: "No", depression: 1 },
  { id: 23, gender: "Male", age: 19, city: "Agra", profession: "Student", academicPressure: 1, workPressure: 0, cgpa: 8.6, studySatisfaction: 5, jobSatisfaction: 0, sleepDuration: "More than 8 hours", dietaryHabits: "Healthy", degree: "BBA", suicidalThoughts: "No", workStudyHours: 3, financialStress: 1, familyHistory: "No", depression: 0 },
  { id: 24, gender: "Female", age: 25, city: "Visakhapatnam", profession: "Working Professional", academicPressure: 0, workPressure: 4, cgpa: 6.1, studySatisfaction: 0, jobSatisfaction: 2, sleepDuration: "5-6 hours", dietaryHabits: "Unhealthy", degree: "M.Tech", suicidalThoughts: "Yes", workStudyHours: 10, financialStress: 4, familyHistory: "Yes", depression: 1 },
  { id: 25, gender: "Male", age: 22, city: "Mysore", profession: "Student", academicPressure: 3, workPressure: 0, cgpa: 7.4, studySatisfaction: 3, jobSatisfaction: 0, sleepDuration: "7-8 hours", dietaryHabits: "Healthy", degree: "B.Com", suicidalThoughts: "No", workStudyHours: 4, financialStress: 2, familyHistory: "No", depression: 0 },
  { id: 26, gender: "Female", age: 20, city: "Coimbatore", profession: "Student", academicPressure: 5, workPressure: 0, cgpa: 5.5, studySatisfaction: 1, jobSatisfaction: 0, sleepDuration: "Less than 5 hours", dietaryHabits: "Unhealthy", degree: "B.Tech", suicidalThoughts: "Yes", workStudyHours: 9, financialStress: 5, familyHistory: "Yes", depression: 1 },
  { id: 27, gender: "Male", age: 21, city: "Surat", profession: "Student", academicPressure: 2, workPressure: 0, cgpa: 8.2, studySatisfaction: 4, jobSatisfaction: 0, sleepDuration: "7-8 hours", dietaryHabits: "Healthy", degree: "B.Sc", suicidalThoughts: "No", workStudyHours: 3, financialStress: 1, familyHistory: "No", depression: 0 },
  { id: 28, gender: "Female", age: 24, city: "Ludhiana", profession: "Student", academicPressure: 4, workPressure: 0, cgpa: 6.4, studySatisfaction: 2, jobSatisfaction: 0, sleepDuration: "5-6 hours", dietaryHabits: "Moderate", degree: "MBA", suicidalThoughts: "No", workStudyHours: 7, financialStress: 3, familyHistory: "No", depression: 1 },
  { id: 29, gender: "Male", age: 18, city: "Kanpur", profession: "Student", academicPressure: 3, workPressure: 0, cgpa: 7.8, studySatisfaction: 3, jobSatisfaction: 0, sleepDuration: "7-8 hours", dietaryHabits: "Moderate", degree: "B.Tech", suicidalThoughts: "No", workStudyHours: 5, financialStress: 2, familyHistory: "No", depression: 0 },
  { id: 30, gender: "Female", age: 22, city: "Vadodara", profession: "Student", academicPressure: 5, workPressure: 0, cgpa: 4.9, studySatisfaction: 1, jobSatisfaction: 0, sleepDuration: "Less than 5 hours", dietaryHabits: "Unhealthy", degree: "M.Sc", suicidalThoughts: "Yes", workStudyHours: 10, financialStress: 5, familyHistory: "Yes", depression: 1 },
];
